/**
 * Property-Based Tests for QR payload encryption/decryption.
 *
 * **Validates: Requirements 6.6**
 *
 * Property 1: QR Payload Round-Trip
 * For any valid QRPayload, decryptQRPayload(encryptQRPayload(p)) must deeply equal p.
 */

import { describe, it, beforeAll, expect } from 'vitest';
import * as fc from 'fast-check';
import { encryptQRPayload, decryptQRPayload } from '@/lib/qr';

beforeAll(() => {
  process.env.NEXTAUTH_SECRET = 'test-secret-for-property-tests';
});

describe('QR Payload Round-Trip (Property 1)', () => {
  it('decryptQRPayload(encryptQRPayload(p)) deeply equals p for any valid QRPayload', () => {
    /**
     * **Validates: Requirements 6.6**
     *
     * For any valid QRPayload generated by the arbitrary below,
     * encrypting then decrypting must produce a value deeply equal to the original.
     */
    const qrPayloadArbitrary = fc.record({
      passId: fc.uuid(),
      holderId: fc.uuid(),
      branchId: fc.uuid(),
      passType: fc.constantFrom('gate_pass' as const, 'visitor' as const),
      expiresAt: fc.date().map((d) => d.toISOString()),
    });

    fc.assert(
      fc.property(qrPayloadArbitrary, (payload) => {
        const ciphertext = encryptQRPayload(payload);
        const decrypted = decryptQRPayload(ciphertext);
        expect(decrypted).toEqual(payload);
      }),
      { numRuns: 25 },
    );
  });
});
